--- 
database: workspace_production
default: 
  adapter: sqlite3
  pool: "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>"
  timeout: 5000
development: 
  adapter: sqlite3
  database: db/development.sqlite3
  pool: "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>"
  timeout: 5000
encoding: unicode
password: "<%= ENV['WORKSPACE_DATABASE_PASSWORD'] %>"
pool: "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>"
production: 
  adapter: postgresql
test: 
  adapter: sqlite3
  database: db/test.sqlite3
  pool: "<%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>"
  timeout: 5000
username: workspace